<!DOCTYPE html>
<html lang="en">
<head>
	<!-- title -->
	<?php echo $this->headTitle($this->translate('Sign in to Wolf'))->setSeparator(' - ')->setAutoEscape(false) ?>
	<!-- head meta -->
	<?php echo $this->headMeta()
		->setCharset('utf-8')
		->appendName('viewport', 'width=device-width, initial-scale=1.0')
		->appendName('description', 'Dev2 Admin Panel')
		->appendName('author', 'Dev2 Digital')
		->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
	?>

	<?php echo $this
		->headLink(array(
			'rel' => 'shortcut icon',
			'type' => 'image/vnd.microsoft.icon',
			'href' => $this->basePath() . '/img/favicon.ico'
		))
		->prependStylesheet($this->basePath() . '/css/auth/style.css')
		->prependStylesheet($this->basePath() . '/vendor/neon/assets/css/custom.css')
		->prependStylesheet($this->basePath() . '/vendor/neon/assets/css/neon-forms.css')
		->prependStylesheet($this->basePath() . '/vendor/neon/assets/css/neon-theme.css')
		->prependStylesheet($this->basePath() . '/vendor/neon/assets/css/neon-core.css')
		->prependStylesheet($this->basePath() . '/vendor/neon/assets/css/bootstrap.css')
		->prependStylesheet($this->basePath() . 'http://fonts.googleapis.com/css?family=Noto+Sans:400,700,400italic')
		->prependStylesheet($this->basePath() . '/vendor/neon/assets/css/font-icons/entypo/css/entypo.css')
		->prependStylesheet($this->basePath() . '/vendor/neon/assets/js/jquery-ui/css/no-theme/jquery-ui-1.10.3.custom.min.css')
	?>

	<?php echo $this->headScript()
		->prependFile($this->basePath() . '/vendor/neon/assets/js/neon-demo.js')
		->prependFile($this->basePath() . '/vendor/neon/assets/js/neon-custom.js')
		->prependFile($this->basePath() . '/vendor/neon/assets/js/neon-api.js')
		->prependFile($this->basePath() . '/vendor/neon/assets/js/resizeable.js')
		->prependFile($this->basePath() . '/vendor/neon/assets/js/joinable.js')
		->prependFile($this->basePath() . '/vendor/neon/assets/js/bootstrap.js')
		->prependFile($this->basePath() . '/vendor/neon/assets/js/jquery-ui/js/jquery-ui-1.10.3.minimal.min.js')
		->prependFile($this->basePath() . '/vendor/neon/assets/js/gsap/main-gsap.js')
		->prependFile($this->basePath() . 'https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js',   'text/javascript', array('conditional' => 'lt IE 9',))
		->prependFile($this->basePath() . 'https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
		->prependFile($this->basePath() . '/vendor/neon/assets/js/ie8-responsive-file-warning.js', 'text/javascript', array('conditional' => 'lt IE 9',))
		->prependFile($this->basePath() . '/vendor/neon/assets/js/jquery-1.11.0.min.js')
	;
	?>
</head>
<body class="page-body login-page login-form-fall" data-url="<?php echo $this->serverUrl(); ?>">
		<?php echo $this->content; ?>
</body>
</html>